module.exports = {
    ModuloService: require("./modulo.service"),
    ParteService: require("./parte.service"),
    ObjetoService: require("./objeto.service"),
    SptestService: require("./sptest.service"),
    VersionService: require("./version.service"),
    ContactoService: require("./contacto.service"),
    PartePublicoService: require("./partepublico.service"),
    UsuarioService: require("./usuario.service"),
    HabilitacionService: require("./habilitacion.service"),
    NovedadService: require("./novedad.service"),
    DocumentoService: require("./documento.service"),
    OcurrenciaService: require("./ocurrencia.service"),
    ImpactoService: require("./impacto.service"),
    VotacionService: require("./votacion.service"),
    SecurityService: require("./security.service"),
    ParametroService: require("./parametro.service"),
    LogService: require("./log.service"),
    CursoService: require("./curso.service")
};