module.exports = {
    ModuloController: require("./modulo.controller"),
    ParteController: require("./parte.controller"),
    ObjetoController: require("./objeto.controller"),
    SptestController: require("./sptest.controller"),
    VersionController: require("./version.controller"),
    ContactoController: require("./contacto.controller"),
    PartePublicoController: require("./partepublico.controller"),
    ClienteController: require("./cliente.controller"),
    HabilitacionController: require("./habilitacion.controller"),
    NovedadController: require("./novedad.controller"),
    DocumentoController: require("./documento.controller"),
    OcurrenciaController: require("./ocurrencia.controller"),
    ImpactoController: require("./impacto.controller"),
    ImagenesController: require("./imagenes.controller"),
    IntercambioController: require("./intercambio.controller"),
    VotacionController: require("./votacion.controller"),
    SecurityController: require("./security.controller"),
    ImagenPerfilController: require("./imagenPerfil.controller"),
    LoginController: require("./login.controller"),
    ParametroController: require("./parametro.controller"),
    CursoController: require("./curso.controller"),
    EncuestaController: require("./encuesta.controller"),
    LoginNewController: require("./login-new.controller"),
    EmailEditorController: require("./emailEditor.controller"),
    JobController: require("./job.controller"),
    MenuController: require("./menu.controller")
};