module.exports = {
    ModuloController: require("./modulo.controller"),
    ParteController: require("./parte.controller"),
    ObjetoController: require("./objeto.controller"),
    SptestController: require("./sptest.controller"),
    VersionController: require("./version.controller"),
    ContactoController: require("./contacto.controller"),
    PartePublicoController: require("./partepublico.controller"),
    UsuarioController: require("./usuario.controller"),
    HabilitacionController: require("./habilitacion.controller"),
    NovedadController: require("./novedad.controller"),
    DocumentoController: require("./documento.controller"),
    OcurrenciaController: require("./ocurrencia.controller"),
    ImpactoController: require("./impacto.controller"),
    ImagenesController: require("./imagenes.controller"),
    IntercambioController: require("./intercambio.controller"),
    VotacionController: require("./votacion.controller"),
    SecurityController: require("./security.controller"),
    ImagenPerfilController: require("./imagenPerfil.controller"),
    LoginController: require("./login.controller")
};